global:
  output_root: "results"
  embedding_root: "../../numerical_representation_data/"

dataset:
  name: "antioxidant_proteins"
  input_data: "../data/sequences.csv"
  sequence_col: "sequence"
  id_col: "id"
  label_col: "label"

experiment:
  name: "onehot_experiment"

representation:
  enabled: true
  run_embedding: true   
  method: "sylphy_one_hot"
  model: "one_hot"
  model_alias: "one_hot"
  encoder: "one_hot"
  output_format: "csv"

splits:
  random_kfold:
    enabled: true
    biosieve_exec: "biosieve"
    strategy: "random_kfold"
    n_splits: 5
    shuffle: true
    seed: 13
    val_size: 0.1

  stratified_kfold:
    enabled: true
    biosieve_exec: "biosieve"
    strategy: "stratified_kfold"
    n_splits: 5
    shuffle: true
    seed: 13
    val_size: 0.1
    dropna: true
    cast_to_str: false