[build-system]
requires = ["hatchling>=1.24"]
build-backend = "hatchling.build"

[project]
name = "building_models"
version = "0.2.0"
description = "Implemented library for preparing, processing, training, and applying predictive models for protein science."
readme = "README.md"
requires-python = ">=3.11,<4.0"
license = { file = "LICENSE" }

authors = [
    { name = "Kren AI Lab", email = "krenai@umag.cl" }
]

maintainers = [
    { name = "Kren AI Lab", email = "krenai@umag.cl" }
]

classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]

keywords = [
    "bioinformatics",
    "etl",
    "parser",
    "biological datasets",
    "protein",
    "peptide",
]

dependencies = [
    "numpy==2.4.6",
    "pandas==3.0.2",
    "scipy==1.17.1",
    "scikit-learn==1.8.0",
    "xgboost==3.2.0",
    "matplotlib==3.10.8",
    "snakemake==9.19.0",
    "sylphy[all]==0.2.0",
    "biosieve==0.1.0",
    "biopython==1.82",
    "tqdm==4.70.0",
    "requests==2.34.2",
    "rcsb-api==1.7.3",
    "python-dotenv",
    "pyyaml==6.0.3",
    "typer",
    "openpyxl==3.1.5",
    "seaborn==0.13.2",
]

[project.urls]
Homepage = "https://github.com/kren-ai-lab/protein_ml_decision_analysis"
Repository = "https://github.com/kren-ai-lab/protein_ml_decision_analysis"
Issues = "https://github.com/kren-ai-lab/protein_ml_decision_analysis"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/building_models"]
