#!/usr/bin/env python3

from __future__ import annotations

import argparse
import shutil
import subprocess
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import yaml


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run Biosieve distance-aware embedding k-fold splits for each reduction threshold "
            "listed in reduction_summary.csv, validate class presence in folds, and keep only valid runs."
        )
    )

    parser.add_argument(
        "--reduction-summary",
        required=True,
        help="Path to reduction_summary.csv generated by the reduction runner."
    )
    parser.add_argument(
        "--reduction-dir",
        required=True,
        help="Base directory containing one folder per threshold (e.g. p30_0, p40_0, ...)."
    )
    parser.add_argument(
        "--full-data",
        required=True,
        help=(
            "Original full dataset containing metadata + embedding columns "
            "(.csv or .parquet)."
        )
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Directory where split outputs will be written."
    )

    parser.add_argument(
        "--feature-prefix",
        default="p_",
        help="Prefix of embedding feature columns in full-data. Default: p_"
    )
    parser.add_argument(
        "--label-col",
        default="label",
        help="Label column. Default: label"
    )
    parser.add_argument(
        "--id-col",
        default="id",
        help="Identifier column used to align reduced data and embeddings. Default: id"
    )

    parser.add_argument(
        "--biosieve-exec",
        default="biosieve",
        help="Biosieve executable name. Default: biosieve"
    )
    parser.add_argument(
        "--strategy",
        default="distance_aware_kfold",
        help="Split strategy. Default: distance_aware_kfold"
    )

    parser.add_argument(
        "--n-splits",
        type=int,
        default=5,
        help="Number of folds. Default: 5"
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=13,
        help="Seed for the splitter. Default: 13"
    )
    parser.add_argument(
        "--val-size",
        type=float,
        default=0.1,
        help="Validation fraction inside train. Default: 0.1"
    )
    parser.add_argument(
        "--metric",
        default="cosine",
        help="Distance metric for splitting. Default: cosine"
    )
    parser.add_argument(
        "--shuffle-ties",
        action="store_true",
        help="Enable shuffle_ties in the splitter."
    )

    return parser.parse_args()


def read_table(path: str | Path) -> pd.DataFrame:
    path = Path(path)

    if not path.exists():
        raise FileNotFoundError(f"Input file not found: {path}")

    if path.suffix.lower() == ".csv":
        return pd.read_csv(path)

    if path.suffix.lower() == ".parquet":
        return pd.read_parquet(path)

    raise ValueError(
        f"Unsupported input format for '{path}'. "
        "Supported formats are: .csv, .parquet"
    )


def sanitize_percentile_name(value: float | int | str) -> str:
    return f"p{str(value).replace('.', '_')}"


def write_yaml(data: dict[str, Any], path: Path) -> None:
    with open(path, "w") as f:
        yaml.safe_dump(data, f, sort_keys=False)


def run_command(cmd: list[str]) -> None:
    print("Running:")
    print(" ".join(cmd))
    subprocess.run(cmd, check=True)


def build_split_config(
    embeddings_path: Path,
    ids_path: Path,
    n_splits: int,
    seed: int,
    val_size: float,
    metric: str,
    shuffle_ties: bool,
) -> dict[str, Any]:
    return {
        "distance_aware_kfold": {
            "feature_mode": "embeddings",
            "metric": metric,
            "n_splits": int(n_splits),
            "seed": int(seed),
            "shuffle_ties": bool(shuffle_ties),
            "val_size": float(val_size),
            "embeddings_path": str(embeddings_path),
            "ids_path": str(ids_path),
        }
    }


def get_feature_columns(df: pd.DataFrame, prefix: str) -> list[str]:
    feature_cols = [c for c in df.columns if c.startswith(prefix)]
    if not feature_cols:
        raise ValueError(
            f"No feature columns starting with '{prefix}' were found. "
            f"Available columns: {df.columns.tolist()}"
        )

    try:
        return sorted(feature_cols, key=lambda x: int(x.split("_")[1]))
    except Exception:
        return sorted(feature_cols)


def validate_full_dataframe(df: pd.DataFrame, id_col: str, label_col: str) -> None:
    if id_col not in df.columns:
        raise ValueError(
            f"Column '{id_col}' not found in full-data. "
            f"Available columns: {df.columns.tolist()}"
        )

    if label_col not in df.columns:
        raise ValueError(
            f"Column '{label_col}' not found in full-data. "
            f"Available columns: {df.columns.tolist()}"
        )

    if df[id_col].isna().any():
        n_missing = int(df[id_col].isna().sum())
        raise ValueError(
            f"Column '{id_col}' in full-data contains {n_missing} missing values."
        )

    if df[id_col].duplicated().any():
        n_dup = int(df[id_col].duplicated().sum())
        raise ValueError(
            f"Column '{id_col}' in full-data contains {n_dup} duplicated values. "
            "It must be unique to align embeddings correctly."
        )


def validate_reduced_dataframe(df: pd.DataFrame, id_col: str, label_col: str, source: Path) -> None:
    if id_col not in df.columns:
        raise ValueError(
            f"Column '{id_col}' not found in {source}. "
            f"Columns: {df.columns.tolist()}"
        )

    if label_col not in df.columns:
        raise ValueError(
            f"Column '{label_col}' not found in {source}. "
            f"Columns: {df.columns.tolist()}"
        )

    if df[id_col].isna().any():
        n_missing = int(df[id_col].isna().sum())
        raise ValueError(
            f"Column '{id_col}' in {source} contains {n_missing} missing values."
        )

    if df.columns.duplicated().any():
        dup_cols = df.columns[df.columns.duplicated()].tolist()
        raise ValueError(
            f"{source} contains duplicated columns: {dup_cols}"
        )


def build_reduced_embedding_artifacts(
    df_full: pd.DataFrame,
    df_reduced: pd.DataFrame,
    id_col: str,
    feature_cols: list[str],
    out_embeddings_npy: Path,
    out_ids_csv: Path,
) -> tuple[pd.DataFrame, np.ndarray]:
    if id_col not in df_reduced.columns:
        raise ValueError(
            f"Column '{id_col}' not found in reduced dataframe. "
            f"Available columns: {df_reduced.columns.tolist()}"
        )

    if df_reduced[id_col].isna().any():
        n_missing = int(df_reduced[id_col].isna().sum())
        raise ValueError(
            f"Reduced dataframe contains {n_missing} missing values in '{id_col}'."
        )

    if df_reduced[id_col].duplicated().any():
        n_dup = int(df_reduced[id_col].duplicated().sum())
        raise ValueError(
            f"Reduced dataframe contains {n_dup} duplicated values in '{id_col}'. "
            "Reduced datasets must contain unique representatives only."
        )

    reduced_ids = df_reduced[id_col].tolist()
    df_full_indexed = df_full.set_index(id_col, drop=False)

    missing_ids = [x for x in reduced_ids if x not in df_full_indexed.index]
    if missing_ids:
        raise ValueError(
            f"{len(missing_ids)} reduced ids were not found in full-data. "
            f"Example missing id: {missing_ids[0]}"
        )

    df_selected = df_full_indexed.loc[reduced_ids].copy()
    df_selected = df_selected.loc[:, ~df_selected.columns.duplicated()]

    X = df_selected[feature_cols].astype(float).values

    np.save(out_embeddings_npy, X)
    pd.DataFrame({"id": df_selected[id_col].values}).to_csv(out_ids_csv, index=False)

    return df_selected, X


def detect_split_files(split_dir: Path) -> list[Path]:
    return sorted(split_dir.rglob("*.csv"))


def classify_split_file(path: Path) -> str | None:
    name = path.name.lower()
    if "train" in name:
        return "train"
    if "val" in name or "valid" in name:
        return "val"
    if "test" in name:
        return "test"
    return None


def validate_split_outputs(
    split_dir: Path,
    label_col: str,
    min_n_classes: int = 2,
) -> tuple[bool, list[str]]:
    problems: list[str] = []
    csv_files = detect_split_files(split_dir)

    if not csv_files:
        problems.append("No CSV files were found in split output directory.")
        return False, problems

    relevant_files = []
    for csv_path in csv_files:
        split_kind = classify_split_file(csv_path)
        if split_kind is not None:
            relevant_files.append((csv_path, split_kind))

    if not relevant_files:
        problems.append("No train/val/test CSV files were detected in split output directory.")
        return False, problems

    for csv_path, split_kind in relevant_files:
        df = pd.read_csv(csv_path)

        if label_col not in df.columns:
            problems.append(f"{csv_path}: missing label column '{label_col}'.")
            continue

        n_classes = df[label_col].dropna().nunique()
        counts = df[label_col].value_counts(dropna=False).to_dict()

        if n_classes < min_n_classes:
            problems.append(
                f"{csv_path}: split '{split_kind}' has only {n_classes} class(es). "
                f"Counts={counts}"
            )

    return len(problems) == 0, problems


def remove_dir(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)


def main() -> None:
    args = parse_args()

    reduction_summary = Path(args.reduction_summary).resolve()
    reduction_dir = Path(args.reduction_dir).resolve()
    full_data_path = Path(args.full_data).resolve()
    output_dir = Path(args.output_dir).resolve()

    output_dir.mkdir(parents=True, exist_ok=True)

    if not reduction_summary.exists():
        raise FileNotFoundError(f"reduction_summary not found: {reduction_summary}")

    if not reduction_dir.exists():
        raise FileNotFoundError(f"reduction_dir not found: {reduction_dir}")

    if not full_data_path.exists():
        raise FileNotFoundError(f"full_data not found: {full_data_path}")

    df_summary = pd.read_csv(reduction_summary)
    df_full = read_table(full_data_path)
    df_full = df_full.loc[:, ~df_full.columns.duplicated()]

    validate_full_dataframe(df=df_full, id_col=args.id_col, label_col=args.label_col)

    feature_cols = get_feature_columns(df_full, args.feature_prefix)

    if "percentile" not in df_summary.columns:
        raise ValueError(
            f"'percentile' column not found in reduction_summary. "
            f"Available columns: {df_summary.columns.tolist()}"
        )

    result_rows = []
    df_summary = df_summary.sort_values("percentile").reset_index(drop=True)

    for _, row in df_summary.iterrows():
        percentile = row["percentile"]
        run_name = sanitize_percentile_name(percentile)

        reduction_run_dir = reduction_dir / run_name
        reduced_csv = reduction_run_dir / "data_nr_labeled.csv"

        if not reduction_run_dir.exists():
            print(f"Skipping percentile {percentile}: reduction directory not found -> {reduction_run_dir}")
            continue

        if not reduced_csv.exists():
            print(f"Skipping percentile {percentile}: reduced labeled file not found -> {reduced_csv}")
            continue

        print(f"\nProcessing percentile={percentile} ({run_name})")

        df_reduced = pd.read_csv(reduced_csv)
        df_reduced = df_reduced.loc[:, ~df_reduced.columns.duplicated()]

        validate_reduced_dataframe(
            df=df_reduced,
            id_col=args.id_col,
            label_col=args.label_col,
            source=reduced_csv,
        )

        n_classes_reduced = df_reduced[args.label_col].dropna().nunique()
        if n_classes_reduced < 2:
            print(
                f"Skipping percentile {percentile}: reduced dataset has only {n_classes_reduced} class(es)."
            )
            result_rows.append({
                "percentile": percentile,
                "run_name": run_name,
                "status": "invalid_reduced_dataset",
                "reason": f"only_{n_classes_reduced}_class"
            })
            continue

        split_run_dir = output_dir / run_name
        split_run_dir.mkdir(parents=True, exist_ok=True)

        split_embeddings_npy = split_run_dir / "embeddings.npy"
        split_ids_csv = split_run_dir / "embedding_ids.csv"
        split_yaml = split_run_dir / "params_split.yaml"

        build_reduced_embedding_artifacts(
            df_full=df_full,
            df_reduced=df_reduced,
            id_col=args.id_col,
            feature_cols=feature_cols,
            out_embeddings_npy=split_embeddings_npy,
            out_ids_csv=split_ids_csv,
        )

        split_cfg = build_split_config(
            embeddings_path=split_embeddings_npy,
            ids_path=split_ids_csv,
            n_splits=args.n_splits,
            seed=args.seed,
            val_size=args.val_size,
            metric=args.metric,
            shuffle_ties=args.shuffle_ties,
        )
        write_yaml(split_cfg, split_yaml)

        try:
            run_command([
                args.biosieve_exec,
                "split",
                "--input-data", str(reduced_csv),
                "--output-dir", str(split_run_dir),
                "--strategy", args.strategy,
                "--id-column", args.id_col,
                "--params", str(split_yaml),
            ])
        except subprocess.CalledProcessError as e:
            print(f"Split failed for percentile {percentile}: {e}")
            remove_dir(split_run_dir)
            result_rows.append({
                "percentile": percentile,
                "run_name": run_name,
                "status": "split_failed",
                "reason": str(e)
            })
            continue

        is_valid, problems = validate_split_outputs(
            split_dir=split_run_dir,
            label_col=args.label_col,
            min_n_classes=2,
        )

        if not is_valid:
            print(f"Invalid split for percentile {percentile}. Removing directory: {split_run_dir}")
            for p in problems:
                print(f"  - {p}")
            remove_dir(split_run_dir)
            result_rows.append({
                "percentile": percentile,
                "run_name": run_name,
                "status": "invalid_split",
                "reason": " | ".join(problems)
            })
            continue

        print(f"Valid split for percentile {percentile}. Keeping directory: {split_run_dir}")
        result_rows.append({
            "percentile": percentile,
            "run_name": run_name,
            "status": "kept",
            "reason": ""
        })

    df_results = pd.DataFrame(result_rows)
    df_results.to_csv(output_dir / "split_summary.csv", index=False)

    kept = (df_results["status"] == "kept").sum() if not df_results.empty else 0
    total = len(df_results)

    print("\nDone.")
    print(f"Summary saved to: {output_dir / 'split_summary.csv'}")
    print(f"Valid split runs kept: {kept}/{total}")


if __name__ == "__main__":
    main()