#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Summarize split_process outputs generated by the unified Snakemake workflow.

This version reads the public seed-level split_summary.csv files located at:

  split_process/<dataset>/<scenario>/<strategy>/seed_<seed>/split_summary.csv

It creates:
  - split_summary_all.csv
  - split_summary_aggregated.csv
  - split_summary_invalid_only.csv
  - split_summary_by_strategy.csv
  - feasibility plots separated by parameter type, so homology thresholds are
    not mixed with distance/descriptor percentiles.
"""

from __future__ import annotations

import argparse
import math
import re
from pathlib import Path

import matplotlib
matplotlib.use("Agg")

import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap
import numpy as np
import pandas as pd


# ---------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------


def str_to_bool(value) -> bool:
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"true", "1", "yes", "y"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create global summary tables and feasibility plots for split_process."
    )
    parser.add_argument("--split-root", required=True, help="Root folder containing split outputs for one dataset.")
    parser.add_argument("--output-dir", required=True, help="Output directory for summary tables and figures.")
    parser.add_argument("--dataset-name", default="", help="Dataset name to use in output tables/figures.")
    parser.add_argument("--fig-format", default="png", choices=["png", "pdf", "svg"])
    parser.add_argument("--dpi", type=int, default=300)
    parser.add_argument(
        "--cmap",
        default="split_feasibility",
        help=(
            "Matplotlib colormap for heatmaps. Use 'split_feasibility' for a custom "
            "red-yellow-green feasibility scale."
        ),
    )
    parser.add_argument("--annotate", default="true", help="Whether to annotate heatmap cells.")
    parser.add_argument(
        "--include-no-threshold",
        default="true",
        help="Whether to include no_threshold scenarios in the no-threshold plot.",
    )
    return parser.parse_args()


# ---------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------


def mkdir_outputs(output_dir: Path) -> tuple[Path, Path]:
    tables_dir = output_dir / "tables"
    figures_dir = output_dir / "figures"
    tables_dir.mkdir(parents=True, exist_ok=True)
    figures_dir.mkdir(parents=True, exist_ok=True)
    return tables_dir, figures_dir


def collect_seed_summary_files(split_root: Path) -> list[Path]:
    files = sorted(split_root.rglob("split_summary.csv"))
    filtered = []
    for path in files:
        # Do not read analysis outputs or hidden temporary status rows.
        if "split_analysis" in path.parts:
            continue
        if "_summary" in path.parts:
            continue
        if any(part.startswith(".") for part in path.parts):
            continue
        filtered.append(path)
    return filtered


def parse_seed_summary_path(path: Path, split_root: Path) -> dict:
    rel = path.relative_to(split_root)
    parts = rel.parts
    if len(parts) < 4:
        raise ValueError(
            f"Unexpected split_summary.csv location: {path}. Expected "
            "<scenario>/<strategy>/seed_<seed>/split_summary.csv"
        )

    scenario = parts[0]
    strategy = parts[1]
    seed_text = parts[2]
    if not seed_text.startswith("seed_"):
        raise ValueError(f"Could not infer seed from path: {path}")

    seed = int(seed_text.replace("seed_", ""))
    return {"scenario": scenario, "strategy": strategy, "seed": seed}


def threshold_to_parameter(reduction_levels: str):
    if pd.isna(reduction_levels):
        return pd.NA
    text = str(reduction_levels).strip()
    if text in {"", "no_threshold", "None", "nan", "<NA>"}:
        return pd.NA
    if text.startswith("p"):
        try:
            return float(text[1:].replace("_", "."))
        except Exception:
            return text
    if text.startswith("threshold_"):
        try:
            return float(text.replace("threshold_", ""))
        except Exception:
            return text
    if text.startswith("minseqid_"):
        try:
            return float(text.replace("minseqid_", "").replace("_", "."))
        except Exception:
            return text
    try:
        return float(text)
    except Exception:
        return text


def infer_parameter_type(row: pd.Series) -> str:
    if "percentile" in row.index and pd.notna(row.get("percentile")) and str(row.get("percentile")).strip() != "":
        return "percentile"
    if "min_seq_id" in row.index and pd.notna(row.get("min_seq_id")) and str(row.get("min_seq_id")).strip() != "":
        return "min_seq_id"

    reduction_levels = str(row.get("reduction_levels", "")).strip()
    if reduction_levels == "no_threshold":
        return "no_threshold"
    if reduction_levels.startswith("p"):
        return "percentile"
    if reduction_levels.startswith(("threshold_", "minseqid_")):
        return "min_seq_id"
    return "parameter"


def infer_parameter_value(row: pd.Series):
    parameter_type = infer_parameter_type(row)
    if parameter_type == "percentile" and "percentile" in row.index:
        return pd.to_numeric(pd.Series([row.get("percentile")]), errors="coerce").iloc[0]
    if parameter_type == "min_seq_id" and "min_seq_id" in row.index:
        return pd.to_numeric(pd.Series([row.get("min_seq_id")]), errors="coerce").iloc[0]
    return threshold_to_parameter(row.get("reduction_levels", ""))


def format_parameter(value) -> str:
    if pd.isna(value):
        return "no_threshold"
    try:
        value_f = float(value)
        if value_f.is_integer():
            return str(int(value_f))
        return f"{value_f:g}"
    except Exception:
        return str(value)


def natural_key(text: str):
    return [int(x) if x.isdigit() else x.lower() for x in re.split(r"(\d+)", str(text))]


def shorten_scenario_name(name: str) -> str:
    out = str(name)
    replacements = {
        "esm2_t6_8M_UR50D": "ESM2-8M",
        "prot_t5_xl_uniref50": "ProtT5-XL",
        "mistral_Prot_v1_134M": "Mistral-Prot",
        "ankh2_ext1": "Ankh2-ext1",
        "esmc_300m": "ESMC-300M",
        "prot_bert": "ProtBERT",
        "one_hot": "One-hot",
        "reduced_distance_by_": "reduced_distance_by_",
        "reduced_descriptor_by_": "reduced_descriptor_by_",
        "reduced_homology": "reduced_homology",
        "no_reduced": "no_reduced",
    }
    for old, new in replacements.items():
        out = out.replace(old, new)
    return out


def get_colormap(name: str):
    if name == "split_feasibility":
        return LinearSegmentedColormap.from_list(
            "split_feasibility",
            [
                (0.00, "#c43c39"),  # invalid / low kept rate
                (0.50, "#f7e6a1"),
                (1.00, "#2a9d62"),  # valid / high kept rate
            ],
        )
    return plt.get_cmap(name)


# ---------------------------------------------------------------------
# Loading and tables
# ---------------------------------------------------------------------


def read_seed_summary(path: Path, split_root: Path, dataset_name: str) -> pd.DataFrame:
    meta = parse_seed_summary_path(path, split_root)
    df = pd.read_csv(path)
    if df.empty:
        return df

    if "reduction_levels" not in df.columns:
        raise ValueError(f"Missing reduction_levels column in {path}. Columns={df.columns.tolist()}")
    if "status" not in df.columns:
        raise ValueError(f"Missing status column in {path}. Columns={df.columns.tolist()}")
    if "reason" not in df.columns:
        df["reason"] = ""

    df.insert(0, "dataset_name", dataset_name)
    df.insert(1, "scenario", meta["scenario"])
    df.insert(2, "strategy", meta["strategy"])
    df.insert(3, "seed", meta["seed"])
    df["split_summary_file"] = str(path)

    parameter_types = []
    parameter_values = []
    for _, row in df.iterrows():
        ptype = infer_parameter_type(row)
        pval = infer_parameter_value(row)
        parameter_types.append(ptype)
        parameter_values.append(pval)

    df["parameter_type"] = parameter_types
    df["parameter_value"] = parameter_values
    df["threshold"] = df["reduction_levels"].where(df["reduction_levels"].astype(str) != "no_threshold", "")
    df["status"] = df["status"].fillna("unknown").astype(str)
    df["reason"] = df["reason"].fillna("").astype(str)
    df["is_kept"] = (df["status"] == "kept").astype(int)
    df["is_invalid"] = (df["status"] != "kept").astype(int)
    return df


def load_all_summaries(summary_files: list[Path], split_root: Path, dataset_name: str) -> pd.DataFrame:
    frames = []
    for path in summary_files:
        try:
            df = read_seed_summary(path, split_root, dataset_name)
        except Exception as exc:
            print(f"[WARNING] Could not read {path}: {exc}")
            continue
        if not df.empty:
            frames.append(df)

    if not frames:
        raise RuntimeError("No readable seed-level split_summary.csv files were found.")

    out = pd.concat(frames, ignore_index=True)
    out["parameter_value"] = pd.to_numeric(out["parameter_value"], errors="coerce")
    return out


def build_aggregated_summary(df: pd.DataFrame) -> pd.DataFrame:
    group_cols = [
        "dataset_name",
        "scenario",
        "strategy",
        "parameter_type",
        "threshold",
        "parameter_value",
        "reduction_levels",
    ]

    agg = (
        df.groupby(group_cols, dropna=False)
        .agg(
            n_total=("status", "size"),
            n_kept=("is_kept", "sum"),
            n_invalid=("is_invalid", "sum"),
            seeds=("seed", lambda x: ";".join(map(str, sorted(set(map(int, x))))))
        )
        .reset_index()
    )
    agg["kept_rate"] = agg["n_kept"] / agg["n_total"].replace(0, pd.NA)
    agg["invalid_rate"] = agg["n_invalid"] / agg["n_total"].replace(0, pd.NA)

    sort_param = pd.to_numeric(agg["parameter_value"], errors="coerce")
    agg["_sort_param"] = sort_param.fillna(-1)
    agg = agg.sort_values(["strategy", "parameter_type", "scenario", "_sort_param", "reduction_levels"]).drop(columns=["_sort_param"])
    return agg.reset_index(drop=True)


def build_strategy_summary(df: pd.DataFrame) -> pd.DataFrame:
    out = (
        df.groupby(["dataset_name", "strategy"], dropna=False)
        .agg(
            n_total=("status", "size"),
            n_kept=("is_kept", "sum"),
            n_invalid=("is_invalid", "sum"),
            n_scenarios=("scenario", "nunique"),
            n_seeds=("seed", "nunique"),
        )
        .reset_index()
    )
    out["kept_rate"] = out["n_kept"] / out["n_total"].replace(0, pd.NA)
    out["invalid_rate"] = out["n_invalid"] / out["n_total"].replace(0, pd.NA)
    return out.sort_values("strategy").reset_index(drop=True)


# ---------------------------------------------------------------------
# Plots
# ---------------------------------------------------------------------


def style_axis(ax) -> None:
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.tick_params(axis="both", labelsize=9)


def parameter_type_label(parameter_type: str) -> str:
    if parameter_type == "percentile":
        return "Reduction percentile"
    if parameter_type == "min_seq_id":
        return "Homology min_seq_id"
    if parameter_type == "no_threshold":
        return "No reduction"
    return "Reduction parameter"


def parameter_type_slug(parameter_type: str) -> str:
    if parameter_type == "min_seq_id":
        return "homology"
    return parameter_type


def plot_heatmap(
    agg: pd.DataFrame,
    strategy: str,
    parameter_type: str,
    output_path: Path,
    dataset_name: str,
    cmap_name: str,
    annotate: bool,
    dpi: int,
) -> bool:
    sub = agg[(agg["strategy"] == strategy) & (agg["parameter_type"] == parameter_type)].copy()
    if sub.empty:
        return False

    sub["column_label"] = sub["parameter_value"].map(format_parameter)
    sub.loc[sub["reduction_levels"] == "no_threshold", "column_label"] = "no_threshold"
    sub["scenario_label"] = sub["scenario"].map(shorten_scenario_name)

    pivot = sub.pivot_table(
        index="scenario_label",
        columns="column_label",
        values="kept_rate",
        aggfunc="mean",
    )

    if pivot.empty:
        return False

    row_order = sorted(pivot.index.tolist(), key=natural_key)

    def col_sort_key(x):
        if x == "no_threshold":
            return (-1, x)
        try:
            return (float(x), x)
        except Exception:
            return (999999, x)

    col_order = sorted(pivot.columns.tolist(), key=col_sort_key)
    pivot = pivot.loc[row_order, col_order]

    values = pivot.values.astype(float)
    masked_values = np.ma.masked_invalid(values)

    n_rows, n_cols = pivot.shape
    fig_w = max(7.5, 0.75 * n_cols + 3.8)
    fig_h = max(3.4, 0.58 * n_rows + 2.4)

    cmap = get_colormap(cmap_name).copy()
    cmap.set_bad(color="#f2f2f2")

    fig, ax = plt.subplots(figsize=(fig_w, fig_h))
    im = ax.imshow(masked_values, aspect="auto", cmap=cmap, vmin=0, vmax=1)

    ax.set_xticks(np.arange(n_cols))
    ax.set_xticklabels(pivot.columns.tolist(), rotation=45, ha="right")
    ax.set_yticks(np.arange(n_rows))
    ax.set_yticklabels(pivot.index.tolist())

    ax.set_xlabel(parameter_type_label(parameter_type))
    ax.set_ylabel("Scenario")
    ax.set_title(
        f"Split feasibility\nDataset: {dataset_name} | Strategy: {strategy} | {parameter_type_label(parameter_type)}"
    )

    ax.set_xticks(np.arange(-0.5, n_cols, 1), minor=True)
    ax.set_yticks(np.arange(-0.5, n_rows, 1), minor=True)
    ax.grid(which="minor", color="white", linestyle="-", linewidth=1.1)
    ax.tick_params(which="minor", bottom=False, left=False)

    if annotate:
        for i in range(n_rows):
            for j in range(n_cols):
                val = pivot.iloc[i, j]
                if pd.isna(val):
                    continue
                val = float(val)
                text_color = "white" if val <= 0.18 or val >= 0.82 else "#1a1a1a"
                ax.text(j, i, f"{val:.2f}", ha="center", va="center", fontsize=8.5, color=text_color)

    cbar = fig.colorbar(im, ax=ax, fraction=0.035, pad=0.035)
    cbar.set_label("Kept rate")

    fig.tight_layout()
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)
    return True


def plot_strategy_overview(strategy_summary: pd.DataFrame, output_path: Path, dataset_name: str, dpi: int) -> None:
    if strategy_summary.empty:
        return

    df = strategy_summary.sort_values("strategy").copy()
    x = np.arange(df.shape[0])

    fig, ax = plt.subplots(figsize=(max(7.5, 1.25 * len(x)), 4.6))
    bars = ax.bar(x, df["kept_rate"], color="#5aa9a7", edgecolor="#2f6f73", linewidth=0.8)
    ax.set_ylim(0, 1.05)
    ax.set_xticks(x)
    ax.set_xticklabels(df["strategy"], rotation=35, ha="right")
    ax.set_ylabel("Kept rate")
    ax.set_title(f"Overall split feasibility\nDataset: {dataset_name}")
    ax.grid(axis="y", alpha=0.25)
    style_axis(ax)

    for bar, val in zip(bars, df["kept_rate"]):
        if pd.notna(val):
            ax.text(
                bar.get_x() + bar.get_width() / 2,
                min(float(val) + 0.03, 1.03),
                f"{float(val):.2f}",
                ha="center",
                va="bottom",
                fontsize=9,
            )

    fig.tight_layout()
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------


def main() -> None:
    args = parse_args()

    split_root = Path(args.split_root).expanduser().resolve()
    output_dir = Path(args.output_dir).expanduser().resolve()
    dataset_name = args.dataset_name or split_root.name
    annotate = str_to_bool(args.annotate)
    include_no_threshold = str_to_bool(args.include_no_threshold)

    if not split_root.exists():
        raise FileNotFoundError(f"split_root does not exist: {split_root}")

    tables_dir, figures_dir = mkdir_outputs(output_dir)

    summary_files = collect_seed_summary_files(split_root)
    if not summary_files:
        raise RuntimeError(f"No seed-level split_summary.csv files found under: {split_root}")

    print(f"[INFO] Found {len(summary_files)} seed-level split_summary.csv files")

    all_status = load_all_summaries(summary_files, split_root=split_root, dataset_name=dataset_name)
    all_path = tables_dir / "split_summary_all.csv"
    all_status.to_csv(all_path, index=False)
    print(f"[INFO] Saved: {all_path}")

    aggregated = build_aggregated_summary(all_status)
    agg_path = tables_dir / "split_summary_aggregated.csv"
    aggregated.to_csv(agg_path, index=False)
    print(f"[INFO] Saved: {agg_path}")

    invalid = all_status[all_status["status"] != "kept"].copy()
    invalid_path = tables_dir / "split_summary_invalid_only.csv"
    invalid.to_csv(invalid_path, index=False)
    print(f"[INFO] Saved: {invalid_path}")

    strategy_summary = build_strategy_summary(all_status)
    strategy_path = tables_dir / "split_summary_by_strategy.csv"
    strategy_summary.to_csv(strategy_path, index=False)
    print(f"[INFO] Saved: {strategy_path}")

    parameter_types = sorted(
        aggregated["parameter_type"].dropna().unique().tolist(),
        key=lambda x: {"no_threshold": 0, "min_seq_id": 1, "percentile": 2}.get(x, 9),
    )

    for strategy in sorted(aggregated["strategy"].dropna().unique().tolist()):
        for parameter_type in parameter_types:
            if parameter_type == "no_threshold" and not include_no_threshold:
                continue
            slug = parameter_type_slug(parameter_type)
            fig_path = figures_dir / f"split_feasibility__{strategy}__{slug}.{args.fig_format}"
            created = plot_heatmap(
                agg=aggregated,
                strategy=strategy,
                parameter_type=parameter_type,
                output_path=fig_path,
                dataset_name=dataset_name,
                cmap_name=args.cmap,
                annotate=annotate,
                dpi=args.dpi,
            )
            if created:
                print(f"[INFO] Saved: {fig_path}")

    overview_path = figures_dir / f"split_feasibility_overall_by_strategy.{args.fig_format}"
    plot_strategy_overview(strategy_summary, overview_path, dataset_name=dataset_name, dpi=args.dpi)
    print(f"[INFO] Saved: {overview_path}")

    done = output_dir / "analysis.done"
    done.write_text("done\n", encoding="utf-8")
    print(f"[INFO] Done marker: {done}")


if __name__ == "__main__":
    main()
