#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Summarize data-reduction outputs generated by the unified Snakemake workflow.

The script creates two complementary analyses:

1. General reduction analysis
   - Standardizes reduction_summary.csv files from embedding-distance,
     one-hot descriptor, and homology reductions.
   - Reports retained/removed percentages for each reduction threshold.
   - Generates a panel figure with retained vs removed percentages.

2. Label-aware reduction analysis
   - Reads each reduced dataset listed in the summary files.
   - Counts how many sequences from each label are retained.
   - Computes retained percentages per label relative to the original dataset.
   - Generates a panel figure showing label-specific retention.

The script is intentionally tolerant to slightly different summary schemas. It tries
common column names and searches for sibling files such as data_nr_labeled.csv when
needed.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path
from typing import Iterable

import matplotlib
matplotlib.use("Agg")

import matplotlib.pyplot as plt
import pandas as pd


COLOR_RETAINED = "#83c5be"
COLOR_REMOVED = "#e9a37f"


# ---------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate general and label-aware summaries for reduction outputs."
    )

    parser.add_argument(
        "--reduction-summary",
        action="append",
        required=True,
        help=(
            "Reduction summary specification in the form: "
            "<label>::<kind>::<path>. Can be repeated. "
            "Example: ESM2-8M::embedding_distance::/path/reduction_summary.csv"
        ),
    )
    parser.add_argument("--input-data", required=True, help="Original unreduced dataset CSV.")
    parser.add_argument("--dataset-name", required=True, help="Dataset name.")
    parser.add_argument("--label-col", default="label", help="Label column name.")
    parser.add_argument("--id-col", default="id", help="Sequence/sample identifier column name.")
    parser.add_argument("--sequence-col", default="sequence", help="Sequence column name.")
    parser.add_argument("--output-dir", required=True, help="Output directory for tables and figures.")
    parser.add_argument("--fig-format", default="png", choices=["png", "pdf", "svg"])
    parser.add_argument("--dpi", type=int, default=300)
    parser.add_argument("--general", action="store_true", help="Run general retained/removed analysis.")
    parser.add_argument("--by-label", action="store_true", help="Run label-aware retained analysis.")

    return parser.parse_args()


# ---------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------


def parse_summary_spec(spec: str) -> tuple[str, str, Path]:
    parts = spec.split("::", 2)
    if len(parts) != 3:
        raise ValueError(
            "Invalid --reduction-summary format. Expected: <label>::<kind>::<path>. "
            f"Received: {spec}"
        )
    label, kind, path = parts
    return label.strip(), kind.strip(), Path(path).expanduser().resolve()


def first_existing_column(df: pd.DataFrame, candidates: Iterable[str]) -> str | None:
    for col in candidates:
        if col in df.columns:
            return col
    return None


def as_float_series(series: pd.Series) -> pd.Series:
    return pd.to_numeric(series, errors="coerce").astype(float)


def format_parameter(value: float | str) -> str:
    try:
        value_f = float(value)
    except Exception:
        return str(value)

    if value_f.is_integer():
        return str(int(value_f))
    return f"{value_f:g}"


def style_axis(ax) -> None:
    ax.grid(axis="y", alpha=0.25)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.tick_params(axis="both", labelsize=9)


def mkdir_outputs(output_dir: Path) -> tuple[Path, Path]:
    tables_dir = output_dir / "tables"
    figures_dir = output_dir / "figures"
    tables_dir.mkdir(parents=True, exist_ok=True)
    figures_dir.mkdir(parents=True, exist_ok=True)
    return tables_dir, figures_dir


# ---------------------------------------------------------------------
# Summary standardization
# ---------------------------------------------------------------------


def infer_parameter_columns(df: pd.DataFrame, kind: str) -> tuple[str, str]:
    if "percentile" in df.columns:
        return "percentile", "percentile"
    if "min_seq_id" in df.columns:
        return "min_seq_id", "min_seq_id"
    if "threshold" in df.columns:
        parameter_type = "min_seq_id" if kind == "homology" else "threshold"
        return parameter_type, "threshold"
    if "parameter_value" in df.columns:
        return df.get("parameter_type", pd.Series(["parameter"])).iloc[0], "parameter_value"

    raise ValueError(
        "Could not infer a parameter column. Expected one of: "
        "percentile, min_seq_id, threshold, parameter_value. "
        f"Available columns: {df.columns.tolist()}"
    )


def infer_count_columns(df: pd.DataFrame) -> tuple[str | None, str | None]:
    n_input_col = first_existing_column(
        df,
        ["n_input", "n_in", "n_total", "input_n", "total_input", "n_before"],
    )
    n_reduced_col = first_existing_column(
        df,
        ["n_reduced", "n_out", "n_kept", "kept_n", "n_after", "n_retained"],
    )
    return n_input_col, n_reduced_col


def infer_retained_fraction(df: pd.DataFrame) -> pd.Series:
    fraction_col = first_existing_column(
        df,
        ["kept_fraction", "retained_fraction", "fraction_kept", "kept_frac"],
    )
    if fraction_col is not None:
        values = as_float_series(df[fraction_col])
        # If values look like percentages, convert to fractions.
        if values.dropna().max() > 1.5:
            values = values / 100.0
        return values

    retained_percent_col = first_existing_column(
        df,
        ["retained_percent", "kept_percent", "percent_retained"],
    )
    if retained_percent_col is not None:
        return as_float_series(df[retained_percent_col]) / 100.0

    n_input_col, n_reduced_col = infer_count_columns(df)
    if n_input_col is not None and n_reduced_col is not None:
        n_input = as_float_series(df[n_input_col])
        n_reduced = as_float_series(df[n_reduced_col])
        return n_reduced / n_input.replace(0, pd.NA)

    raise ValueError(
        "Could not infer retained fraction. Expected kept_fraction, retained_percent, "
        "or n_input/n_reduced-like columns. "
        f"Available columns: {df.columns.tolist()}"
    )


def _deduplicate_paths(paths: list[Path]) -> list[Path]:
    seen = set()
    out = []
    for path in paths:
        key = str(path)
        if key in seen:
            continue
        seen.add(key)
        out.append(path)
    return out


def _parameter_folder_candidates(value: float | str, kind: str, parameter_type: str) -> list[str]:
    """
    Build folder-name candidates from a reduction parameter.

    Examples
    --------
    30.0 -> p30_0, p30
    99.5 -> p99_5
    0.7  -> threshold_0.7
    """
    value_raw = str(value).strip()

    try:
        value_f = float(value)
    except Exception:
        value_f = None

    candidates: list[str] = []

    if kind == "homology" or parameter_type in {"min_seq_id", "threshold"}:
        if value_f is not None:
            candidates.extend([
                f"threshold_{value_f:g}",
                f"threshold_{value_f}",
            ])
        candidates.append(f"threshold_{value_raw}")
        return list(dict.fromkeys(candidates))

    # Distance-based reductions use folders such as p30_0, p99_5, p99_9.
    if value_f is not None:
        candidates.extend([
            "p" + str(float(value_f)).replace(".", "_"),  # 30.0 -> p30_0
            "p" + f"{value_f:g}".replace(".", "_"),       # 30.0 -> p30
        ])

    candidates.append("p" + value_raw.replace(".", "_"))
    return list(dict.fromkeys(candidates))


def _existing_reduced_file(folder: Path, kind: str) -> Path | None:
    """
    Return the preferred reduced dataset file inside a threshold folder.
    """
    if kind == "homology":
        names = [
            "data_nr_labeled.csv",
            "data_nr_mmseqs2_labeled.csv",
            "data_nr_mmseqs2.csv",
            "data_nr.csv",
        ]
    else:
        names = [
            "data_nr_labeled.csv",
            "data_nr.csv",
        ]

    for name in names:
        path = folder / name
        if path.exists():
            return path.resolve()

    return None


def infer_reduced_dataset_path(
    row: pd.Series,
    summary_path: Path,
    kind: str,
    parameter_type: str,
    parameter_value: float | str,
) -> Path | None:
    """
    Infer the path to the reduced dataset for one row of a reduction summary.

    Priority:
    1. Use explicit path columns if present in the summary CSV.
    2. Resolve relative paths with respect to the summary CSV parent directory.
    3. Infer sibling threshold folders from the parameter value:
       - p30_0/data_nr_labeled.csv for distance/descriptor reductions.
       - threshold_0.7/data_nr_mmseqs2.csv for homology reductions.
    """
    path_cols = [
        "reduced_dataset_labeled",
        "data_nr_labeled",
        "labeled_dataset",
        "reduced_labeled_dataset",
        "reduced_dataset",
        "data_nr",
        "output_data",
        "output_csv",
    ]

    summary_parent = summary_path.parent

    for col in path_cols:
        if col not in row.index:
            continue
        value = row[col]
        if pd.isna(value) or str(value).strip() == "":
            continue

        raw_path = Path(str(value)).expanduser()

        path_candidates = []
        if raw_path.is_absolute():
            path_candidates.append(raw_path)
        else:
            path_candidates.extend([
                summary_parent / raw_path,
                Path.cwd() / raw_path,
                raw_path,
            ])

        for path in _deduplicate_paths(path_candidates):
            if path.exists():
                sibling = path.parent / "data_nr_labeled.csv"
                if sibling.exists():
                    return sibling.resolve()
                return path.resolve()

            sibling = path.parent / "data_nr_labeled.csv"
            if sibling.exists():
                return sibling.resolve()

    # Fallback: infer from the folder structure generated by the reduction workflow.
    for folder_name in _parameter_folder_candidates(parameter_value, kind, parameter_type):
        folder = summary_parent / folder_name
        found = _existing_reduced_file(folder, kind)
        if found is not None:
            return found

    return None


def standardize_summary(label: str, kind: str, path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Reduction summary not found: {path}")

    df = pd.read_csv(path)
    if df.empty:
        raise ValueError(f"Reduction summary is empty: {path}")

    parameter_type, parameter_col = infer_parameter_columns(df, kind)
    retained_fraction = infer_retained_fraction(df)
    n_input_col, n_reduced_col = infer_count_columns(df)

    out = pd.DataFrame(index=df.index)
    out["dataset_reduction_label"] = label
    out["reduction_kind"] = kind
    out["parameter_type"] = parameter_type
    out["parameter_value"] = as_float_series(df[parameter_col])
    out["retained_fraction"] = retained_fraction
    out["retained_percent"] = retained_fraction * 100.0
    out["removed_percent"] = 100.0 - out["retained_percent"]
    out["summary_file"] = str(path)

    if n_input_col is not None:
        out["n_input"] = pd.to_numeric(df[n_input_col], errors="coerce")
    else:
        out["n_input"] = pd.NA

    if n_reduced_col is not None:
        out["n_reduced"] = pd.to_numeric(df[n_reduced_col], errors="coerce")
    else:
        out["n_reduced"] = pd.NA

    reduced_paths = []
    for idx, row in df.iterrows():
        parameter_value = out.loc[idx, "parameter_value"]
        reduced_path = infer_reduced_dataset_path(
            row=row,
            summary_path=path,
            kind=kind,
            parameter_type=str(parameter_type),
            parameter_value=parameter_value,
        )
        reduced_paths.append(str(reduced_path) if reduced_path is not None else "")
    out["reduced_dataset"] = reduced_paths

    out = out.sort_values("parameter_value").reset_index(drop=True)
    return out


# ---------------------------------------------------------------------
# General analysis
# ---------------------------------------------------------------------


def plot_general_panel(df: pd.DataFrame, output_path: Path, dpi: int) -> None:
    labels = list(df["dataset_reduction_label"].drop_duplicates())
    n_panels = len(labels)
    ncols = min(3, max(1, n_panels))
    nrows = math.ceil(n_panels / ncols)

    fig, axes = plt.subplots(
        nrows=nrows,
        ncols=ncols,
        figsize=(4.2 * ncols, 3.4 * nrows),
        squeeze=False,
    )
    axes_flat = axes.flatten()

    legend_handles = None
    legend_labels = None

    for ax, label in zip(axes_flat, labels):
        sub = df[df["dataset_reduction_label"] == label].copy()
        sub = sub.sort_values("parameter_value")
        x = list(range(len(sub)))
        xticklabels = [format_parameter(v) for v in sub["parameter_value"]]

        ax.bar(x, sub["retained_percent"], color=COLOR_RETAINED, label="Retained")
        ax.bar(
            x,
            sub["removed_percent"],
            bottom=sub["retained_percent"],
            color=COLOR_REMOVED,
            label="Removed",
        )

        parameter_type = str(sub["parameter_type"].iloc[0])
        xlabel = "Percentile" if parameter_type == "percentile" else parameter_type

        ax.set_ylim(0, 100)
        ax.set_title(label)
        ax.set_xticks(x)
        ax.set_xticklabels(xticklabels, rotation=45, ha="right")
        ax.set_xlabel(xlabel)
        ax.set_ylabel("Dataset composition (%)")
        style_axis(ax)

        if legend_handles is None:
            legend_handles, legend_labels = ax.get_legend_handles_labels()

    for ax in axes_flat[n_panels:]:
        ax.axis("off")

    if legend_handles is not None:
        fig.legend(
            legend_handles,
            legend_labels,
            loc="lower center",
            ncol=2,
            frameon=True,
            bbox_to_anchor=(0.5, -0.02),
        )

    fig.tight_layout()
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


# ---------------------------------------------------------------------
# Label analysis
# ---------------------------------------------------------------------


def compute_label_summary(
    standardized_df: pd.DataFrame,
    input_data: Path,
    label_col: str,
    id_col: str = "id",
    sequence_col: str = "sequence",
) -> pd.DataFrame:
    if not input_data.exists():
        raise FileNotFoundError(f"Original input data not found: {input_data}")

    original = pd.read_csv(input_data)
    if label_col not in original.columns:
        raise ValueError(
            f"Label column '{label_col}' not found in original input data. "
            f"Available columns: {original.columns.tolist()}"
        )

    before_counts = original[label_col].value_counts(dropna=False).rename("n_before_label")
    n_before_total = int(original.shape[0])

    rows = []

    for _, row in standardized_df.iterrows():
        reduced_path_raw = str(row.get("reduced_dataset", "")).strip()
        if not reduced_path_raw:
            print(
                f"[WARNING] Missing reduced dataset path for "
                f"{row['dataset_reduction_label']} {row['parameter_value']}. Skipping label analysis."
            )
            continue

        reduced_path = Path(reduced_path_raw)
        if not reduced_path.exists():
            print(f"[WARNING] Reduced dataset not found: {reduced_path}. Skipping.")
            continue

        reduced = pd.read_csv(reduced_path)
        if label_col not in reduced.columns:
            sibling = reduced_path.parent / "data_nr_labeled.csv"
            if sibling.exists():
                reduced = pd.read_csv(sibling)
                reduced_path = sibling

        if label_col not in reduced.columns:
            # Fallback: recover labels from the original dataset using id or sequence.
            join_col = None
            if id_col in reduced.columns and id_col in original.columns:
                join_col = id_col
            elif sequence_col in reduced.columns and sequence_col in original.columns:
                join_col = sequence_col

            if join_col is not None:
                label_lookup = original[[join_col, label_col]].drop_duplicates(subset=[join_col])
                reduced = reduced.merge(label_lookup, on=join_col, how="left")

        if label_col not in reduced.columns:
            print(
                f"[WARNING] Label column '{label_col}' not found in {reduced_path}, "
                "and labels could not be recovered from the original dataset. "
                "Skipping this threshold."
            )
            continue

        after_counts = reduced[label_col].value_counts(dropna=False).rename("n_after_label")
        n_after_total = int(reduced.shape[0])

        labels = sorted(set(before_counts.index.tolist()) | set(after_counts.index.tolist()), key=str)
        for label_value in labels:
            n_before_label = int(before_counts.get(label_value, 0))
            n_after_label = int(after_counts.get(label_value, 0))
            retained_label_percent = (
                n_after_label / n_before_label * 100.0 if n_before_label > 0 else pd.NA
            )
            rows.append({
                "dataset_reduction_label": row["dataset_reduction_label"],
                "reduction_kind": row["reduction_kind"],
                "parameter_type": row["parameter_type"],
                "parameter_value": row["parameter_value"],
                "label": label_value,
                "n_before_total": n_before_total,
                "n_after_total": n_after_total,
                "n_before_label": n_before_label,
                "n_after_label": n_after_label,
                "retained_label_percent": retained_label_percent,
                "before_label_percent_of_total": n_before_label / n_before_total * 100.0,
                "after_label_percent_of_total": (
                    n_after_label / n_after_total * 100.0 if n_after_total > 0 else pd.NA
                ),
                "reduced_dataset": str(reduced_path),
            })

    if not rows:
        raise RuntimeError(
            "No label-aware rows were generated. Check that reduced datasets exist and contain the label column."
        )

    out = pd.DataFrame(rows)
    return out.sort_values(
        ["dataset_reduction_label", "label", "parameter_value"]
    ).reset_index(drop=True)


def plot_label_retention(df: pd.DataFrame, output_path: Path, dpi: int) -> None:
    panel_labels = list(df["dataset_reduction_label"].drop_duplicates())
    n_panels = len(panel_labels)
    ncols = min(3, max(1, n_panels))
    nrows = math.ceil(n_panels / ncols)

    fig, axes = plt.subplots(
        nrows=nrows,
        ncols=ncols,
        figsize=(4.4 * ncols, 3.4 * nrows),
        squeeze=False,
    )
    axes_flat = axes.flatten()

    for ax, panel_label in zip(axes_flat, panel_labels):
        sub = df[df["dataset_reduction_label"] == panel_label].copy()
        sub = sub.sort_values("parameter_value")

        for label_value, label_df in sub.groupby("label", dropna=False):
            label_df = label_df.sort_values("parameter_value")
            x = list(range(len(label_df)))
            ax.plot(
                x,
                label_df["retained_label_percent"],
                marker="o",
                linewidth=1.7,
                label=str(label_value),
            )

        first_label = sub["label"].iloc[0]
        ref = sub[sub["label"] == first_label].sort_values("parameter_value")
        xticklabels = [format_parameter(v) for v in ref["parameter_value"]]
        parameter_type = str(sub["parameter_type"].iloc[0])
        xlabel = "Percentile" if parameter_type == "percentile" else parameter_type

        ax.set_ylim(0, 105)
        ax.set_title(panel_label)
        ax.set_xticks(list(range(len(xticklabels))))
        ax.set_xticklabels(xticklabels, rotation=45, ha="right")
        ax.set_xlabel(xlabel)
        ax.set_ylabel("Retained per label (%)")
        style_axis(ax)
        ax.legend(title="Label", fontsize=8, title_fontsize=8, frameon=False)

    for ax in axes_flat[n_panels:]:
        ax.axis("off")

    fig.tight_layout()
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------


def main() -> None:
    args = parse_args()

    output_dir = Path(args.output_dir).expanduser().resolve()
    tables_dir, figures_dir = mkdir_outputs(output_dir)

    standardized_parts = []
    for spec in args.reduction_summary:
        label, kind, summary_path = parse_summary_spec(spec)
        print(f"[INFO] Reading {kind}: {summary_path}")
        standardized_parts.append(standardize_summary(label, kind, summary_path))

    standardized = pd.concat(standardized_parts, ignore_index=True)
    standardized.insert(0, "dataset_name", args.dataset_name)

    standardized_path = tables_dir / "reduction_summary_standardized.csv"
    standardized.to_csv(standardized_path, index=False)
    print(f"[INFO] Saved standardized summary: {standardized_path}")

    if args.general:
        general_fig = figures_dir / f"reduction_retained_removed_percent.{args.fig_format}"
        plot_general_panel(standardized, general_fig, args.dpi)
        print(f"[INFO] Saved general figure: {general_fig}")

    if args.by_label:
        label_summary = compute_label_summary(
            standardized_df=standardized,
            input_data=Path(args.input_data).expanduser().resolve(),
            label_col=args.label_col,
            id_col=args.id_col,
            sequence_col=args.sequence_col,
        )
        label_summary.insert(0, "dataset_name", args.dataset_name)

        label_summary_path = tables_dir / "reduction_summary_by_label.csv"
        label_summary.to_csv(label_summary_path, index=False)
        print(f"[INFO] Saved label summary: {label_summary_path}")

        label_fig = figures_dir / f"reduction_retained_by_label.{args.fig_format}"
        plot_label_retention(label_summary, label_fig, args.dpi)
        print(f"[INFO] Saved label figure: {label_fig}")

    done = output_dir / "analysis.done"
    done.write_text("done\n", encoding="utf-8")
    print(f"[INFO] Done marker: {done}")


if __name__ == "__main__":
    main()
