#!/usr/bin/env python3

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path
from typing import Any

import pandas as pd
import yaml


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run Biosieve embedding_cosine reduction for thresholds read from a percentiles CSV, "
            "using outputs generated by the embedding analysis script."
        )
    )

    parser.add_argument(
        "--embedding-npy",
        required=True,
        help="Path to training_embeddings.npy generated by the embedding analysis script."
    )
    parser.add_argument(
        "--percentiles-csv",
        required=True,
        help="CSV with percentile and similarity columns generated by the embedding analysis script."
    )
    parser.add_argument(
        "--input-data",
        required=True,
        help=(
            "Original CSV used as input for biosieve reduce. "
            "This should contain the ID column and label column, e.g. sequence,label,id,p_0,..."
        )
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Directory where one folder per threshold will be created."
    )

    parser.add_argument(
        "--ids-csv",
        default=None,
        help=(
            "Optional path to ids.csv aligned with embedding.npy. "
            "If not provided, it will be generated automatically from --input-data and --id-col."
        )
    )

    parser.add_argument(
        "--label-col",
        default="label",
        help="Name of the label/response column. Default: label"
    )
    parser.add_argument(
        "--id-col",
        default="sequence",
        help="Column used to match reduced data with original labeled data. Default: sequence"
    )
    parser.add_argument(
        "--threshold-col",
        default="similarity",
        help="Column in percentiles CSV to use as reduction threshold. Default: similarity"
    )
    parser.add_argument(
        "--percentile-col",
        default="percentile",
        help="Column in percentiles CSV containing percentile values. Default: percentile"
    )
    parser.add_argument(
        "--biosieve-exec",
        default="biosieve",
        help="Biosieve executable name. Default: biosieve"
    )
    parser.add_argument(
        "--strategy",
        default="embedding_cosine",
        help="Reducer strategy. Default: embedding_cosine"
    )
    parser.add_argument(
        "--n-jobs",
        type=int,
        default=8,
        help="n_jobs for reducer."
    )
    parser.add_argument(
        "--use-faiss",
        action="store_true",
        help="Use FAISS in reducer."
    )

    return parser.parse_args()


def write_yaml(data: dict[str, Any], path: Path) -> None:
    with open(path, "w") as f:
        yaml.safe_dump(data, f, sort_keys=False)


def run_command(cmd: list[str]) -> None:
    print("Running:")
    print(" ".join(cmd))
    subprocess.run(cmd, check=True)


def sanitize_percentile_name(value: float | int | str) -> str:
    return f"p{str(value).replace('.', '_')}"


def build_reduce_config(
    embedding_npy: Path,
    ids_csv: Path,
    threshold: float,
    use_faiss: bool,
    n_jobs: int,
) -> dict[str, Any]:
    return {
        "embedding_cosine": {
            "embeddings_path": str(embedding_npy),
            "ids_path": str(ids_csv),
            "threshold": float(threshold),
            "use_faiss": bool(use_faiss),
            "n_jobs": int(n_jobs),
        }
    }


def build_ids_csv(df_input: pd.DataFrame, id_col: str, out_path: Path) -> Path:
    """
    Build an ids.csv file aligned with the embedding matrix order.
    It preserves the row order of input_data.
    """
    if id_col not in df_input.columns:
        raise ValueError(
            f"Column '{id_col}' not found in input data. "
            f"Available columns: {df_input.columns.tolist()}"
        )

    if df_input[id_col].isna().any():
        n_missing = int(df_input[id_col].isna().sum())
        raise ValueError(
            f"Column '{id_col}' contains {n_missing} missing values. "
            "IDs must be complete to align with embedding.npy."
        )

    if df_input[id_col].duplicated().any():
        n_dup = int(df_input[id_col].duplicated().sum())
        raise ValueError(
            f"Column '{id_col}' contains {n_dup} duplicated values. "
            "IDs must be unique to align correctly with embedding.npy."
        )

    df_ids = pd.DataFrame({id_col: df_input[id_col].values})
    df_ids.to_csv(out_path, index=False)
    return out_path


def main() -> None:
    args = parse_args()

    embedding_npy = Path(args.embedding_npy).resolve()
    percentiles_csv = Path(args.percentiles_csv).resolve()
    input_data = Path(args.input_data).resolve()
    output_dir = Path(args.output_dir).resolve()

    if args.ids_csv is not None:
        ids_csv = Path(args.ids_csv).resolve()
    else:
        ids_csv = None

    output_dir.mkdir(parents=True, exist_ok=True)

    if not embedding_npy.exists():
        raise FileNotFoundError(f"embedding_npy not found: {embedding_npy}")

    if not percentiles_csv.exists():
        raise FileNotFoundError(f"percentiles_csv not found: {percentiles_csv}")

    if not input_data.exists():
        raise FileNotFoundError(f"input_data not found: {input_data}")

    df_percentiles = pd.read_csv(percentiles_csv)
    df_input = pd.read_csv(input_data)

    if args.percentile_col not in df_percentiles.columns:
        raise ValueError(
            f"Column '{args.percentile_col}' not found in percentiles CSV. "
            f"Available columns: {df_percentiles.columns.tolist()}"
        )

    if args.threshold_col not in df_percentiles.columns:
        raise ValueError(
            f"Column '{args.threshold_col}' not found in percentiles CSV. "
            f"Available columns: {df_percentiles.columns.tolist()}"
        )

    if args.id_col not in df_input.columns:
        raise ValueError(
            f"Column '{args.id_col}' not found in input data. "
            f"Available columns: {df_input.columns.tolist()}"
        )

    if args.label_col not in df_input.columns:
        raise ValueError(
            f"Column '{args.label_col}' not found in input data. "
            f"Available columns: {df_input.columns.tolist()}"
        )

    # If ids_csv is not provided, generate it automatically from input_data
    if ids_csv is None:
        ids_csv = output_dir / "ids.csv"
        build_ids_csv(df_input=df_input, id_col=args.id_col, out_path=ids_csv)
        print(f"Generated ids.csv automatically at: {ids_csv}")
    else:
        if not ids_csv.exists():
            raise FileNotFoundError(f"ids_csv not found: {ids_csv}")

    df_percentiles = df_percentiles.sort_values(args.percentile_col).reset_index(drop=True)

    summary_rows = []

    for _, row in df_percentiles.iterrows():
        percentile = row[args.percentile_col]
        threshold = row[args.threshold_col]

        run_name = sanitize_percentile_name(percentile)
        run_dir = output_dir / run_name
        run_dir.mkdir(parents=True, exist_ok=True)

        reduce_yaml = run_dir / "params_reducer.yaml"
        data_nr_csv = run_dir / "data_nr.csv"
        map_csv = run_dir / "map.csv"
        report_json = run_dir / "report.json"
        labeled_csv = run_dir / "data_nr_labeled.csv"

        reduce_cfg = build_reduce_config(
            embedding_npy=embedding_npy,
            ids_csv=ids_csv,
            threshold=float(threshold),
            use_faiss=args.use_faiss,
            n_jobs=args.n_jobs,
        )
        write_yaml(reduce_cfg, reduce_yaml)

        run_command([
            args.biosieve_exec,
            "reduce",
            "--in", str(input_data),
            "--out", str(data_nr_csv),
            "--map", str(map_csv),
            "--report", str(report_json),
            "--strategy", args.strategy,
            "--params", str(reduce_yaml),
        ])

        if not data_nr_csv.exists():
            raise FileNotFoundError(
                f"Biosieve finished but reduced file was not found for percentile {percentile}: {data_nr_csv}"
            )

        df_reduced = pd.read_csv(data_nr_csv)

        if args.id_col not in df_reduced.columns:
            raise ValueError(
                f"Column '{args.id_col}' not found in reduced data for percentile {percentile}. "
                f"Reduced columns: {df_reduced.columns.tolist()}"
            )

        # Keep only unique mapping of id -> label from original input
        df_labels = df_input[[args.id_col, args.label_col]].drop_duplicates()

        # If reduced file already contains label, preserve it but overwrite safely by merge if needed
        if args.label_col in df_reduced.columns:
            df_reduced = df_reduced.drop(columns=[args.label_col])

        df_reduced_labeled = df_reduced.merge(
            df_labels,
            on=args.id_col,
            how="left",
        )

        df_reduced_labeled.to_csv(labeled_csv, index=False)

        if df_reduced_labeled[args.label_col].isna().any():
            n_missing = int(df_reduced_labeled[args.label_col].isna().sum())
            print(
                f"Warning: {n_missing} reduced rows could not be matched to labels "
                f"for percentile {percentile}."
            )

        label_counts = df_reduced_labeled[args.label_col].value_counts(dropna=False).to_dict()

        summary_row = {
            "percentile": percentile,
            "threshold": float(threshold),
            "n_original": int(len(df_input)),
            "n_reduced": int(len(df_reduced_labeled)),
            "removed": int(len(df_input) - len(df_reduced_labeled)),
            "kept_fraction": float(len(df_reduced_labeled) / len(df_input)),
        }

        for label, count in label_counts.items():
            safe_label = str(label).replace(" ", "_").replace("/", "_")
            summary_row[f"n_{safe_label}"] = int(count)

        summary_rows.append(summary_row)

    df_summary = pd.DataFrame(summary_rows)
    df_summary = df_summary.sort_values("percentile").reset_index(drop=True)
    df_summary.to_csv(output_dir / "reduction_summary.csv", index=False)

    print("Done.")
    print(f"Summary saved to: {output_dir / 'reduction_summary.csv'}")


if __name__ == "__main__":
    main()